name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - run: |
          gem install bundler
          bundle install
          npm install
          npm run build
          JEKYLL_ENV=production bundle exec jekyll build
      - uses: actions/upload-pages-artifact@v1
        with:
          path: './_site'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v1
