name: Deploy Jekyll to GitHub Pages

on:
  push:
    branches: [ master ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby (Jekyll)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'  # ✅ phiên bản Ruby mới nhất ổn định
          bundler-cache: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # ✅ bản LTS mới nhất đến 6/2025

      - run: |
          npm install
          npm run build
          JEKYLL_ENV=production bundle exec jekyll build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: './_site'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
#nhannd1